export const CIRCUIT_OPEN_THRESHOLD = 3;
export const CIRCUIT_PROBE_INTERVAL_SEC = 1800; // 30 min

export const API_KEY_DEFAULT_RATE_LIMIT_PER_MINUTE = 120;
export const API_KEY_MIN_RATE_LIMIT_PER_MINUTE = 1;
export const API_KEY_MAX_RATE_LIMIT_PER_MINUTE = 10_000;
export const API_KEY_DEFAULT_EXPIRY_SEC = 90 * 24 * 60 * 60;
export const API_KEY_DEPENDENCY_RETRY_AFTER_SEC = 60;

export const FEEDBACK_RATE_LIMIT_WINDOW_SEC = 600;
export const FEEDBACK_RATE_LIMIT_MAX_SUBMISSIONS = 3;
