import type { PricingSourceRegistryEntry } from "./pricing-source-registry-types";
import { definePricingSource, PRICING_SOURCE_PRESETS } from "./pricing-source-registry-presets";

export const PRICING_SOURCE_REGISTRY_MARKET_FEEDS = [
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "cg-ticker",
    label: "CoinGecko ticker",
    shortLabel: "CG-ticker",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 2,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "geckoterminal",
    label: "GeckoTerminal",
    shortLabel: "GT",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    requiresObservedAt: false,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardOracle, {
    key: "pyth",
    label: "Pyth Network",
    shortLabel: "Pyth",
    maxTrustedAgeSec: 5 * 60,
    defaultWeight: 2,
    capabilities: {
      hasUpstreamTimestamp: true,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "binance",
    label: "Binance",
    shortLabel: "Binance",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    capabilities: {
      hasBidAsk: false,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: true,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "kraken",
    label: "Kraken",
    shortLabel: "Kraken",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "bitstamp",
    label: "Bitstamp",
    shortLabel: "Bitstamp",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 1,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
    defaultObservedAtMode: "upstream",
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: true,
      isLastTradeOnly: false,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "coinbase",
    label: "Coinbase",
    shortLabel: "Coinbase",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
    defaultObservedAtMode: "upstream",
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: true,
      isLastTradeOnly: false,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardOracle, {
    key: "redstone",
    label: "RedStone",
    shortLabel: "RedStone",
    maxTrustedAgeSec: 5 * 60,
    defaultWeight: 1,
    capabilities: {
      hasUpstreamTimestamp: true,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardProtocol, {
    key: "curve-onchain",
    label: "Curve on-chain",
    shortLabel: "Curve",
    maxTrustedAgeSec: 300,
    defaultWeight: 3,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
    defaultObservedAtMode: "upstream",
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardProtocol, {
    key: "curve-oracle",
    label: "Curve oracle",
    shortLabel: "Curve oracle",
    maxTrustedAgeSec: 300,
    defaultWeight: 3,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
  }),
] as const satisfies readonly PricingSourceRegistryEntry[];
