import type { PricingSourceRegistryEntry } from "./pricing-source-registry-types";

type RequiredPricingSourceFields = "key" | "label" | "shortLabel" | "maxTrustedAgeSec" | "defaultWeight";
type PricingSourcePreset = Omit<PricingSourceRegistryEntry, RequiredPricingSourceFields | "capabilities" | "isProtocolOverride" | "bypassesSoftValidationGuardrails">;
type PricingSourceInput = Pick<PricingSourceRegistryEntry, RequiredPricingSourceFields>
  & Partial<Omit<PricingSourceRegistryEntry, RequiredPricingSourceFields>>;

export function definePricingSource(
  preset: PricingSourcePreset,
  input: PricingSourceInput,
): PricingSourceRegistryEntry {
  return { ...preset, ...input };
}

export const PRICING_SOURCE_PRESETS = {
  softAggregator: {
    trustTier: "soft_aggregator",
    freshnessKind: "local_fetch",
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  softDex: {
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  fallbackSearch: {
    trustTier: "fallback_search",
    freshnessKind: "local_fetch",
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: true,
    defaultObservedAtMode: "local_fetch",
  },
  hardMarket: {
    trustTier: "hard_market",
    freshnessKind: "local_fetch",
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  hardOracle: {
    trustTier: "hard_oracle",
    freshnessKind: "upstream",
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: true,
    supportsUpstreamObservedAt: true,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "upstream",
  },
  hardProtocol: {
    trustTier: "hard_protocol",
    freshnessKind: "local_fetch",
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  cachedReplay: {
    trustTier: "cached_replay",
    freshnessKind: "unknown",
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: null,
  },
} as const satisfies Record<string, PricingSourcePreset>;
