import type { VisualCue } from "./world-types";

/** Non-semantic scene additions audited beside, but excluded from, cue parity. */
export const DECORATIVE_VISUAL_NOTES = {
  engawaForeground: "The engawa foreground, its framing timbers and near-bank planting carry no meaning; they compose the garden threshold without encoding world data.",
  engawaKoi: "The four koi in the calm engawa shallows carry no meaning; they displace the former reflection-basin koi without adding a draw.",
  heroWaterfall: "The engawa waterfall and its plunge foam carry no meaning; one authored fall displaces the broad random silver-water accents.",
  landRim: "The authored land rim, shore shoulders and garden frame carry no meaning; the authoritative water field, steles, labels and accessibility ledger own classification.",
  sharedGardenWind: "Rim pines, island niwaki pads and reeds carry no meaning; their former rigidity is displaced by the existing shared weather breath and gust, with no new oscillator.",
  shakkeiSky: "The borrowed shakkei mountains, haze seam and visible sky layers carry no meaning; they provide depth and atmosphere without encoding freshness, risk or category.",
  seasonalLandmarks: "Petals over the calm shallows and the heron, lantern-round and meteor landmark sightings carry no meaning; they displace the former island-centred dressing without adding draws or ember lanes.",
  seaEdgeGeography: "Named-water banks, reeds, bars, cliff, piles and inlet stones carry no meaning; the authoritative water field and existing DOM ledger remain the classification.",
} as const;

export const LEGEND_MARK_ROWS = [
  {
    cueId: "cue.pigeonnier.notable-movers",
    label: "Pigeonnier watch",
    text: "Pigeons circle above today's notable supply movers. Birds at the loft count today's recorded depeg events (up to twelve visible); the Pigeonnier detail compares the exact count with yesterday and names every watched ship. No birds never certifies calm: unavailable data is stated in the detail and ledger.",
  },
  {
    cueId: "cue.world.epistemic-haze",
    label: "Haze over instruments",
    text: "Low haze over the named risk waters means the Peg summary feed is stale; haze over the built quays means the Chains feed is stale. Clear water or stone means that feed is current. The haze reports evidence age, not market danger or weather.",
  },
  {
    cueId: "cue.ship.age-patina",
    label: "Even hull patina",
    text: "An evenly weathered hull and faint verdigris on fittings mean a longer service or tracking history: under one year is fresh, one to three years seasoned, and over three years veteran. This is separate from the banded salt wear of rough risk water. A neutral finish can mean age evidence is unavailable; the In service since / tracked row says which.",
  },
  {
    cueId: "cue.ship.zone-weathering",
    label: "Weathered hull",
    text: "Warning and Danger water can darken the hull; it marks rough risk water, not permanent damage or safety.",
  },
  {
    cueId: "cue.ship.issuance-work",
    label: "Cargo working each ship",
    text: "Working lighters and davits show that ship's own 24-hour issuance: net minting loads cargo aboard and settles the hull deeper; net redemption discharges it and lets the hull rise. One raised crane lift marks the largest reported event. No workset means either balanced issuance or no per-coin row; the Issuance work, 24h detail row says which.",
  },
  {
    cueId: "cue.ship.seaworthiness-fittings",
    label: "Ship fittings",
    text: "Lifeboats swung out show immediate redemption capacity; sealed chests mark stronger collateral quality while mixed open crates mark weaker or bridged collateral; a customs brand at the plimsoll line means the asset can be blacklisted. Missing report-card inputs leave the corresponding fitting neutral, and the three ship detail rows state each reading.",
  },
  {
    cueId: "cue.dock.congestion",
    label: "Stacked crates",
    text: "Cargo crates on a dock mean chain backing is narrowing or concentrated; empty quays do not certify safety.",
  },
  {
    cueId: "cue.dock.cargo-tide",
    label: "Cargo working the quay",
    text: "A single course of canvas-topped crates out along a harbour's pier means that chain's stablecoins were net minted over 24 hours; the same crates standing back along the quay edge mean they were net burned. An empty harbour means either nothing moved or issuance is not measured there, and the Net flow 24h row says which.",
  },
  {
    cueId: "cue.fleet.flight-to-quality",
    label: "Tenders working the big hulls",
    text: "Small open boats standing off the largest ships and running in on them mean capital is concentrating into the biggest, most trusted stablecoins; how far in they carry is how pronounced the reading is. The boats are harbour craft, not stablecoins — they carry no rig, cannot be selected, and are not counted in the fleet. An empty sea means either no such rotation or no issuance feed, and the lighthouse Flight to quality row says which.",
  },
  {
    cueId: "cue.lighthouse.signal-mast",
    label: "Observatory signal mast",
    text: "Small pennants on the mast beside the observatory count the coins currently off peg (five is the top of the hoist); a dark cone joins them when the worst deviation is large. It reports today's readings, not a forecast.",
  },
  {
    cueId: "cue.world.supply-tide",
    label: "Tide line on the shore rock",
    text: "A dark band of wet stone on the island rock and the quay walls, measured against a fixed iron datum notch: a strandline above the notch means stablecoin supply shrank over the week, below it means supply grew. Bare stone with no notch at all means no chain data arrived.",
  },
  {
    cueId: "cue.lighthouse.high-water-mark",
    label: "Pale band on the lighthouse rocks",
    text: "A pale salt line climbing the lighthouse terrace records the worst index band of the last 30 days — how high the water got, not how it stands now. Unstained rock can also mean there was no history to read.",
  },
  {
    cueId: "cue.lighthouse.garden-month-record",
    label: "The island records the month",
    text: "A calm trailing month opens blossoms and greens the moss; a stressed month makes the planting shed and brown. This is a slow 30-day record, not today's PSI state or an alarm. The lighthouse Garden record, 30d row names the reading and missing history leaves a neutral garden.",
  },
  {
    cueId: "cue.lighthouse.lamp-status",
    label: "Harbor light",
    text: "The lighthouse lamp is steady and warm when all seven source groups are fresh; it becomes perceptibly cooler and slower when some are stale; it dims clearly when every source group is stale and the API is unreachable. This status overlays the PSI band rather than replacing its color or character, and the Harbor light detail row gives the as-of time.",
  },
  {
    cueId: "cue.ship.cross-bearing-buoy",
    label: "Striped cross-bearing buoy",
    text: "A small black-and-white buoy riding beside a ship means its DEX price and its consensus price disagree. It says the two readings differ, not which one is right, and most ships have no buoy because no cross-check was run.",
  },
  {
    cueId: "cue.ship.peg-trim",
    label: "How she rides",
    text: "A hull sitting high out of the water is trading above its peg; one sitting low and heavy is trading below it. Only coins at least 50 bps off par are trimmed at all, the trim is small by design and reads when you are looking at a ship rather than at the whole fleet, and a level hull can mean either at par or no fresh peg reading — the Peg deviation row says which.",
  },
  {
    cueId: "cue.ship.audit-shield",
    label: "Steel-and-gold shield",
    text: "Major graded ships may carry a bluechip audit shield; the shield is a grade marker, not a blanket approval.",
  },
  {
    cueId: "cue.ship.nav-signal",
    label: "Blue mast signal",
    text: "A blue signal square marks a NAV-priced ledger asset — priced by attestation, not market peg; it is a pricing model, not a warning.",
  },
  {
    cueId: "cue.ship.yield-signal",
    label: "Green mast signal",
    text: "A green signal square with a gold pennant marks a yield-bearing coin; it says nothing about peg safety.",
  },
] as const;

export function buildVisualCueRegistry(): VisualCue[] {
  return [
    {
      id: "cue.world.epistemic-haze",
      target: { kind: "area" },
      primaryChannels: ["opacity", "position"],
      visual: "localized low height-fog haze over DEWS risk waters when Peg summary is stale, masked by the existing sea-region field inside the existing water material",
      sourceField: "freshness.pegSummaryStale",
      questionAnswered: "Is the Peg summary reading behind the risk waters current?",
      failureState: "clear named risk waters; no explicit stale flag means no haze is invented",
      domEquivalent: "selected risk-water detail 'Risk-water haze' row when stale, plus the accessibility ledger Instrument haze row and legend mark",
      reducedMotionEquivalent: "the same static localized haze at a fixed time-zero noise pose; no drift is required to carry the cue",
    },
    {
      id: "cue.dock.epistemic-haze",
      target: { kind: "dock" },
      primaryChannels: ["opacity", "position"],
      visual: "localized low height-fog haze over built quays when Chains is stale, applied through the existing quay materials",
      sourceField: "freshness.chainsStale",
      questionAnswered: "Is the Chains reading behind the quays current?",
      failureState: "clear quays; no explicit stale flag means no haze is invented",
      domEquivalent: "selected dock detail 'Quay haze' row when stale, plus the accessibility ledger Instrument haze row and legend mark",
      reducedMotionEquivalent: "the same static localized haze; no motion is needed to carry the cue",
    },
    {
      id: "cue.pigeonnier.notable-movers",
      target: { kind: "pigeonnier" },
      primaryChannels: ["motion", "position", "size"],
      visual: "one pigeon circling above each ship selected by the canonical notable-movers rule, plus a roof roost whose visible bird count follows today's fleet depeg-event count up to a stated cap of twelve",
      sourceField: "stablecoins.peggedAssets[].circulating current/prevDay via selectNotableMovers; pegSummary.summary.depegEventsToday; pegSummary.summary.depegEventsYesterday",
      questionAnswered: "Which ships moved notably today, and did the fleet record more or fewer depeg events than yesterday?",
      failureState: "empty roost and no circling birds; the Pigeonnier detail and accessibility ledger state that the peg summary is unavailable and list no movers rather than implying calm",
      domEquivalent: "Pigeonnier detail Depeg roost and Notable movers rows, in-world mover member links, and the matching accessibility-ledger pigeonnier clauses",
      reducedMotionEquivalent: "static representative roost at the pigeonnier; mover names and exact today-versus-yesterday counts remain in the detail and ledger",
    },
    {
      id: "cue.lighthouse.psi",
      target: { kind: "lighthouse" },
      primaryChannels: ["glow", "opacity"],
      visual: "lighthouse beacon and beam state",
      sourceField: "stability.current.band",
      questionAnswered: "What is the overall Pharos Stability Index state?",
      failureState: "unlit/fogged lighthouse",
      domEquivalent: "lighthouse detail Score, Band, Trend, Composition, and top-contributor rows plus accessibility ledger lighthouse row",
      reducedMotionEquivalent: "static beacon state and lighthouse detail PSI rows",
    },
    {
      id: "cue.lighthouse.lamp-status",
      target: { kind: "lighthouse" },
      primaryChannels: ["color", "motion", "opacity"],
      visual: "Harbor light: steady — all feeds fresh; cooler and slower — some feeds stale; dimmed — API unreachable; showing last-good data. This status is layered over the existing PSI beacon, not a replacement for its PSI color or character",
      sourceField: "freshness.stablecoinsStale, freshness.chainsStale, freshness.stabilityStale, freshness.pegSummaryStale, freshness.stressStale, freshness.reportCardsStale, freshness.mintBurnStale",
      questionAnswered: "Can the live world be trusted as current, is it being held on partly stale feeds, or is the API unreachable behind last-good data?",
      failureState: "dimmed lamp with the Harbor light detail row reading 'dimmed — API unreachable; showing last-good data'; the world remains on its last-good data rather than disappearing",
      domEquivalent: "lighthouse detail 'Harbor light' row with the as-of time plus the accessibility-ledger Harbor light clause; the row says steady, cooler and slower, or dimmed in plain language",
      reducedMotionEquivalent: "static lamp temperature, intensity, and composed PSI character; no continuous sweep or flame motion is introduced",
    },
    {
      id: "cue.lighthouse.signal-mast",
      target: { kind: "lighthouse" },
      primaryChannels: ["shape", "size"],
      visual: "signal mast on the observatory terrace flying one small pennant per coin currently off peg (hoist of five) with a dark storm cone at the yardarm when the worst live deviation crosses the shared price-materiality gate",
      sourceField: "pegSummary.summary.activeDepegCount, pegSummary.summary.worstCurrent",
      questionAnswered: "How many stablecoins are off peg across the whole fleet right now, and is any one of them far enough off to count as a storm?",
      failureState: "bare mast; the lighthouse Signal mast row reads 'no peg summary tonight' and the Fleet peg row is absent",
      domEquivalent: "lighthouse detail Signal mast and Fleet peg rows plus the accessibility ledger lighthouse signal-mast clause",
      reducedMotionEquivalent: "same pennants and cone held at their composed time-zero pose",
    },
    {
      id: "cue.lighthouse.high-water-mark",
      target: { kind: "lighthouse" },
      primaryChannels: ["size", "color"],
      visual: "pale salt-crust courses banding the lighthouse terrace, one course per severity step of the worst Pharos Stability Index band reached in the trailing 30 days; bare stone when the worst reading never left the calmest band",
      sourceField: "stability.history[].band",
      questionAnswered: "Is this calm harbour one that has always been calm, or one that recovered from something recently?",
      failureState: "bare stone; the lighthouse 'Worst band, 30d' row reads 'Unstained — no index history to read', which is not the same as never having risen",
      domEquivalent: "lighthouse detail 'Worst band, 30d' row plus the accessibility ledger lighthouse high-water clause",
      reducedMotionEquivalent: "identical — the mark is a static record and never animates at any setting",
    },
    {
      id: "cue.lighthouse.garden-month-record",
      target: { kind: "lighthouse" },
      primaryChannels: ["color", "shape", "size"],
      visual: "existing island shrubs open into sparse blossom colour and the planted terrace moss greens after a calm trailing month; prolonged stress scales the same planting back and turns its moss and foliage toward dry brown",
      sourceField: "stability.history[].score (trailing 30 days)",
      questionAnswered: "Has the fleet spent the month in conditions where the garden could flourish, or has sustained stress weathered it?",
      failureState: "neutral planting and moss; the lighthouse Garden record, 30d row says there is no index history to grow from",
      domEquivalent: "lighthouse detail 'Garden record, 30d' row plus the accessibility-ledger garden-record and slow-tempo clauses",
      reducedMotionEquivalent: "identical static record — it changes only as daily history enters or leaves the trailing window and never animates as an alert",
    },
    {
      id: "cue.lighthouse.beam-dwell",
      target: { kind: "lighthouse" },
      primaryChannels: ["motion", "position"],
      visual: "the beacon's sweep slowing as it crosses the bearing of the ship contributing most to the Pharos Stability Index, so the light lingers there each revolution",
      sourceField: "stability.current.contributors[0]",
      questionAnswered: "Which single ship is doing most to move the fleet-wide index right now?",
      failureState: "an even sweep at the fleet's stress tempo; the Beam bearing row is absent when no contributor is reported",
      domEquivalent: "lighthouse detail Beam bearing row and top-contributor list plus the accessibility ledger beam-bearing clause",
      reducedMotionEquivalent: "no sweep at all — the beam holds a static bearing on that same ship, and the Beam bearing row names which ship it is holding on",
    },
    {
      id: "cue.ship.cross-bearing-buoy",
      target: { kind: "ship" },
      primaryChannels: ["shape", "position"],
      visual: "small black-and-white striped buoy with a crossed topmark riding alongside any ship whose DEX price check disagrees with the consensus feed",
      sourceField: "pegSummary.coins[].dexPriceCheck.agrees",
      questionAnswered: "Are the two independent readings of this coin's price telling the same story?",
      failureState: "no buoy — which covers both 'the readings agree' and 'no check was run'; the detail row appears only on disagreement and the ledger clause only when a check ran at all",
      domEquivalent: "ship detail 'DEX cross-check' row on disagreement, plus the accessibility ledger DEX cross-check clause whenever a check ran",
      reducedMotionEquivalent: "identical — the buoy holds a static stand-off from its hull and moves only when the ship does, which reduced motion already stops",
    },
    {
      id: "cue.dock.size",
      target: { kind: "dock" },
      primaryChannels: ["size", "shape", "position"],
      visual: "shore-station footprint and type at a named rim cove, with Ethereum's boathouse precinct and its available L2 annex pavilions joined by one covered bridge and shared path",
      sourceField: "chains.chains[].id, chains.chains[].totalUsd, chains.chains[].topStablecoins",
      questionAnswered: "Which chains hold major stablecoin supply, which L2s belong to Ethereum harbor, and which stablecoins dominate each chain?",
      failureState: "station unavailable state",
      domEquivalent: "dock detail Station type, Rim cove, Stablecoin supply, Harbor rank, Share of stablecoin supply, Concentration, and harbored-stablecoin rows plus station ledger rows",
      reducedMotionEquivalent: "static station footprint, covered bridge with fixed lantern light, and station ledger rows",
    },
    {
      id: "cue.ship.distance",
      target: { kind: "ship" },
      primaryChannels: ["position", "motion", "opacity"],
      visual: "ship placement from Calm Anchorage through Watch Breakwater, Alert Channel, Warning Shoals, and Danger Strait; within each named DEWS water, score magnitude draws the berth from its calm edge toward its rough edge",
      sourceField: "pegSummary.coins[], stress.signals[].band, stress.signals[].score",
      questionAnswered: "Which stablecoins are under peg or DEWS stress?",
      failureState: "evidence caveat in ship detail",
      domEquivalent: "ship detail placement explanation with named risk water area, zone, Within-zone anchoring, and Stress driver rows plus matching accessibility-ledger clauses",
      reducedMotionEquivalent: "static idle position in the current risk-water area with named risk-water facts in DOM",
    },
    {
      id: "cue.ship.motion",
      target: { kind: "ship" },
      primaryChannels: ["motion", "position", "opacity"],
      visual: "ship route, chain footprint, mooring orbit variation, stale-evidence drift, 24h supply-change wake intensity, per-coin 24h mint/redeem flow intensity as cycle pace, and chain-breadth dwell",
      sourceField: "stablecoins.peggedAssets[].chainCirculating, pegSummary.coins[], stress.signals[], placementEvidence.stale, change24hPct, mintBurn.coins[].flowIntensity, chainPresence.length, ship.id (per-ship mooring orbit phase/radius offset)",
      questionAnswered: "Where can this ship dock, how broad is its chain footprint, which risk water anchors its route, how active is its 24h mint/redeem flow, how recent is its supply change, and how confident is its placement?",
      failureState: "reduced-motion static risk-water idle position with evidence caveat; unavailable flowIntensity uses a neutral 1.0 cycle-speed scalar and the Cycle tempo row says 'Unmeasured — neutral pace'",
      domEquivalent: "ship detail Cycle tempo (24h mint/redeem flow intensity), 24h supply change, Chain footprint (extended dwell suffix), Evidence status facts, plus accessibility ledger ship row with 'cycle pace tracks 24h mint/redeem flow intensity by magnitude, not market-cap tier'",
      reducedMotionEquivalent: "risk-water or Ledger Mooring idle position without RAF",
    },
    {
      id: "cue.water.semantic-terrain",
      target: { kind: "area" },
      primaryChannels: ["color", "shape", "motion"],
      visual: "printed cartographic water labels over calm DEWS anchorage, watch breakwater chop, alert current, warning shoals, storm strait, and ledger-water texture",
      sourceField: "stress.signals[], pegSummary.coins[], stablecoinMeta.flags.navToken",
      questionAnswered: "Which named water areas encode calm, NAV-ledger, alert, warning, or danger conditions?",
      failureState: "generic water texture with DOM area detail still available",
      domEquivalent: "named area detail panel and accessibility ledger rows",
      reducedMotionEquivalent: "static semantic water texture and printed labels",
    },
    {
      // The one cue that reads the SIGN of the peg deviation. `cue.ship.distance`
      // spends its magnitude on which water the ship anchors in and collapses
      // the direction; a premium and a discount are opposite market facts.
      id: "cue.ship.peg-trim",
      target: { kind: "ship" },
      primaryChannels: ["position", "shape"],
      visual: "the hull lifting clear of the water on coins trading above par and settling low and heavy on coins trading below it, in two steps at the same 50 and 200 bps the risk-water placement uses; an even keel below 50 bps and on any stale peg row",
      sourceField: "pegSummary.coins[].currentDeviationBps (sign), freshness.pegSummaryStale",
      questionAnswered: "Is this coin off peg because demand is running ahead of it, or because holders are redeeming out of it?",
      failureState: "even keel — which covers at-par, under the 50 bps gate, and no fresh peg reading alike; the Peg deviation row separates the three",
      domEquivalent: "ship detail 'Peg deviation' row, which names the direction outright and says whether the hull is trimmed for it, plus the matching accessibility-ledger peg-deviation clause",
      reducedMotionEquivalent: "identical — the trim is how the ship floats, not something she does, so there is nothing to freeze",
    },
    {
      // Reliable class reading is inspect-zoom only; fleet-zoom analysis belongs in the Class row and ledger.
      id: "cue.ship.hull",
      target: { kind: "ship" },
      primaryChannels: ["shape", "size"],
      visual: "one of six East-Asian hull-family silhouettes: broad bezaisen carrier, needle kobaya runner, paired-hull council boat, long covered takasebune barge, battened junk fan, or round deep bullion scow",
      sourceField: "stablecoinMeta.flags.governance, stablecoinMeta.flags.backing, stablecoinMeta.flags.yieldBearing, stablecoinMeta.flags.navToken, stablecoinMeta.flags.pegCurrency",
      questionAnswered: "What collateral, peg, yield, and governance family does this stablecoin belong to?",
      failureState: "kobaya-derived unclassified hull; the Class row names the missing classification",
      domEquivalent: "ship detail Class row and accessibility-ledger class clause",
      reducedMotionEquivalent: "same static East-Asian hull-family silhouette",
    },
    {
      id: "cue.ship.issuance-work",
      target: { kind: "ship" },
      primaryChannels: ["position", "shape", "motion"],
      visual: "net-minted ships take cargo aboard from two working lighters, their davits working as the hull settles deeper; net-redeemed ships discharge toward the lighters and ride higher. The reported largest 24h event gets one distinct raised crane lift",
      sourceField: "mintBurn.coins[].netFlow24hUsd, mintBurn.coins[].flowIntensity, mintBurn.coins[].largestEvent24h",
      questionAnswered: "Was this coin's supply minted or redeemed over the last day, how strongly did it move, and what was its largest event?",
      failureState: "no workset and neutral issuance draft when the per-coin row is unavailable; balanced measured flow also has no workset, but the Issuance work, 24h row distinguishes it from missing data",
      domEquivalent: "ship detail 'Issuance work, 24h' row and accessibility-ledger issuance-work clause name direction, net amount, intensity, largest event, and the immediate-truth/render-tempo split",
      reducedMotionEquivalent: "static representative composition with lighters held alongside, the largest-event crane lift held raised, and the final draft applied instantly",
    },
    {
      id: "cue.ship.seaworthiness-fittings",
      target: { kind: "ship" },
      primaryChannels: ["shape", "position"],
      visual: "lifeboats progressively swung out for immediate redemption capacity, sealed treasury chests or mixed open crates for collateral quality, and a customs brand beside the plimsoll line when blacklisting authority exists",
      sourceField: "reportCards.cards[].rawInputs.{redemptionImmediateCapacityRatio,collateralQuality,canBeBlacklisted}",
      questionAnswered: "What immediate redemption capacity, collateral quality, and blacklist authority does this ship's report card record?",
      failureState: "no corresponding fitting when a raw input or the report card is unavailable; the three detail rows explicitly say unavailable",
      domEquivalent: "ship detail Redemption fitting, Collateral cargo, and Customs authority rows plus the matching accessibility-ledger fittings clause",
      reducedMotionEquivalent: "identical static fittings; no motion carries any part of the reading",
    },
    {
      id: "cue.ship.dependency-formation",
      target: { kind: "ship" },
      primaryChannels: ["position", "shape"],
      visual: "a coin with a report-card dependency holds a close formation beside its strongest in-fleet parent",
      sourceField: "reportCards.dependencyGraph.edges[].{from,to,weight,type}",
      questionAnswered: "Which stablecoin depends most strongly on another stablecoin in this fleet?",
      failureState: "ordinary independent route; Dependency formation row absent",
      domEquivalent: "ship detail Dependency formation row and matching accessibility-ledger clause",
      reducedMotionEquivalent: "same static parent-child formation and named relationship",
    },
    {
      id: "cue.ship.scale",
      target: { kind: "ship" },
      primaryChannels: ["size", "shape"],
      visual: "compressed ship scale tier",
      sourceField: "stablecoins.peggedAssets[].circulating",
      questionAnswered: "Roughly how large is the stablecoin supply without letting outliers dominate the map?",
      failureState: "small default scale",
      domEquivalent: "ship detail market-cap row with fleet rank and share-of-fleet plus size-tier row",
      reducedMotionEquivalent: "same static compressed size tier",
    },
    {
      id: "cue.ship.audit-shield",
      target: { kind: "ship" },
      primaryChannels: ["shape", "color"],
      visual: "steel shield with gold chevron beside the signal mast on titan/heritage hulls with a bluechip-graded report card",
      sourceField: "reportCards.cards[].rawInputs.bluechipGrade",
      questionAnswered: "Does this major stablecoin carry a bluechip rating grade?",
      failureState: "no shield; detail row absent without a graded report card",
      domEquivalent: "ship detail Bluechip audit fact (folded into the class panel row) and accessibility ledger line",
      reducedMotionEquivalent: "same static shield",
    },
    {
      id: "cue.ship.nav-signal",
      target: { kind: "ship" },
      primaryChannels: ["shape", "color"],
      visual: "blue signal square with a cream pennant beside the mast on NAV-priced ledger assets",
      sourceField: "stablecoinMeta.flags.navToken",
      questionAnswered: "Is this asset NAV-priced by attestation rather than market-pegged?",
      failureState: "no mast signal; detail row absent for market-pegged coins",
      domEquivalent: "ship detail Class row folded Mast signal fact and accessibility ledger nav-pricing clause",
      reducedMotionEquivalent: "same static mast signal",
    },
    {
      id: "cue.ship.yield-signal",
      target: { kind: "ship" },
      primaryChannels: ["shape", "color"],
      visual: "green signal square with a gold pennant beside the mast on yield-bearing coins without NAV pricing",
      sourceField: "stablecoinMeta.flags.yieldBearing",
      questionAnswered: "Does this coin pay yield to holders?",
      failureState: "no mast signal; detail row absent for non-yield coins",
      domEquivalent: "ship detail Class row folded Mast signal fact and accessibility ledger yield clause",
      reducedMotionEquivalent: "same static mast signal",
    },
    {
      id: "cue.ship.safety-watch",
      target: { kind: "ship" },
      primaryChannels: ["shape", "color"],
      visual: "checkered safety-watch square on ships with D or F report-card grades",
      sourceField: "reportCards.cards[].overallGrade (D/F), reportCards.cards[].dimensions",
      questionAnswered: "Which stablecoins carry a D or F safety grade watch overlay?",
      failureState: "no watch overlay; detail row absent for NR or missing report cards",
      domEquivalent: "ship detail Safety grade plus five seaworthiness dimension rows, with matching accessibility-ledger grade and rationale clauses",
      reducedMotionEquivalent: "same static watch overlay with folded Class row and ledger rationale text",
    },
    {
      id: "cue.dock.congestion",
      target: { kind: "dock" },
      primaryChannels: ["shape", "size"],
      visual: "the station's single works-prop cargo stack occupies the quay edge when chain backing is narrowing or concentrated",
      sourceField: "chains.chains[].healthFactors.backingDiversity",
      questionAnswered: "Is this chain's stablecoin backing diversified or concentrated?",
      failureState: "no crates; dock Backing diversity row absent without the health factor",
      domEquivalent: "station detail Backing diversity row and accessibility ledger line",
      reducedMotionEquivalent: "same static crate stack",
    },
    {
      id: "cue.dock.quay-condition",
      target: { kind: "dock" },
      primaryChannels: ["shape", "color"],
      visual: "the chain health-factor average dresses healthy station masonry in clean granite and trimmed lanterns, while weak stations show darker cracked masonry and one leaning bollard",
      sourceField: "chains.chains[].healthFactors.{concentration,quality,pegStability,backingDiversity,chainEnvironment}",
      questionAnswered: "How seaworthy is this chain's stablecoin harbor across its reported health factors?",
      failureState: "neutral weathered masonry; Quay condition row absent",
      domEquivalent: "dock detail Quay condition row and matching accessibility-ledger clause",
      reducedMotionEquivalent: "identical static masonry and fittings",
    },
    {
      // The WEEKLY flow reading, against the cargo tide's daily one. Kept quiet
      // on purpose: supply growing or shrinking is a condition, not a warning.
      id: "cue.world.supply-tide",
      target: { kind: "lighthouse" },
      primaryChannels: ["position", "color", "size"],
      visual: "a band of dark wet stone on the island's shore rock and on every quay wall, its top edge — the strandline — standing above a fixed iron datum notch when the week's stablecoin supply fell and below it when supply rose; the excursion is compressed against a 2% full scale so an ordinary week still lifts clear of the datum",
      sourceField: "chains.globalChange7dPct",
      questionAnswered: "Did the whole stablecoin supply grow or shrink over the past week?",
      failureState: "bare stone with no datum notch at all — distinct from every real tide state, because a cue that cannot say 'no data' eventually says something false instead",
      domEquivalent: "lighthouse detail 'Supply tide 7d' row naming the direction outright, plus the matching accessibility ledger lighthouse clause",
      reducedMotionEquivalent: "identical — a weekly figure carries no rate to animate, so the band is static at every setting",
    },
    {
      // The world's only DAILY flow cue. Everything else here reports a stock.
      id: "cue.dock.cargo-tide",
      target: { kind: "dock" },
      primaryChannels: ["position", "shape", "size"],
      visual: "a single course of canvas-topped crates standing seaward along a harbour's pier deck when its chains' stablecoins were net minted over 24 hours, and standing landward along the quay's outer edge when they were net burned; the run's length carries how one-sided the day's flow was",
      sourceField: "mintBurn.coins[].netFlow24hUsd, mintBurn.coins[].mintVolume24hUsd, mintBurn.coins[].burnVolume24hUsd, mintBurn.scope.chainIds (allocated across harbours by each coin's chain presence)",
      questionAnswered: "Is stablecoin supply being created or destroyed at this harbour right now?",
      failureState: "no crates — which covers both 'nothing moved' and 'issuance is not measured on this chain'; the Net flow 24h row separates the two rather than leaving an empty quay to mean either",
      domEquivalent: "dock detail 'Net flow 24h' row naming the direction outright plus gross mint and burn, the matching dock accessibility-ledger clause, and the fleet-issuance ledger line above the dock list",
      reducedMotionEquivalent: "identical — the cargo is a standing state and never animates at any setting, so there is nothing to freeze",
    },
    {
      // The mint/burn gauge's other reading, and the fleet-wide one. The cargo
      // tide answers "is supply being made or unmade, here"; this answers
      // "where is it going", which is a question about the fleet rather than
      // about any one quay — hence boats on open water rather than a mark on a
      // harbour. Both are drawn from the same payload and neither repeats the
      // other's statement.
      id: "cue.fleet.flight-to-quality",
      target: { kind: "lighthouse" },
      primaryChannels: ["motion", "position"],
      visual: "small open tenders attending the largest-market-cap hulls while the gauge holds: they come in off open water, lie on station under a hull for minutes at a time, then draw back out and wait their turn. The reported intensity sets HOW MANY of a hull's boats are lying in at any moment, and how close in they lie — a weak reading keeps one or two attending from well out, a strong one has nearly the whole flotilla gathered close under the hull. They carry no rig, no wake and no lantern, are unselectable, and are counted nowhere in the fleet — they are harbour craft, not stablecoins",
      sourceField: "mintBurn.gauge.flightToQuality, mintBurn.gauge.flightIntensity (drawn on the largest ships by stablecoins.peggedAssets[].circulating)",
      questionAnswered: "Is capital leaving the smaller and riskier stablecoins and concentrating into the largest, most trusted ones?",
      failureState: "empty water — nothing is drawn at all, which covers both 'the gauge reports no such rotation' and 'no issuance feed arrived'; the lighthouse 'Flight to quality' row separates the two, and is absent entirely when the gauge never landed",
      domEquivalent: "lighthouse detail 'Flight to quality' row naming the state and the intensity outright, plus the fleet-issuance accessibility-ledger line above the dock list",
      reducedMotionEquivalent: "the flotilla held static as it stands at any instant — the reported intensity's share of each hull's boats lying on station close under it, the rest waiting offshore, bows out. Deterministic, with no clock and no movement, and both halves of the reading (how many attend, how close in they lie) survive the freeze",
    },
    {
      // The chain-level partner to the cargo tide, and deliberately NOT the
      // same statement: the crates below are issuance measured at this quay,
      // this is the chain's total held supply, which also moves when supply
      // bridges in or out without a coin being minted. A harbour can be net
      // burning and still filling. The two marks are kept at different heights
      // and in different forms so that disagreement reads as the real thing it
      // is rather than as one cue contradicting the other.
      id: "cue.dock.harbour-tempo",
      target: { kind: "dock" },
      primaryChannels: ["motion", "position"],
      visual: "gulls working a harbour: they rest on its pier deck between turns and lift off over the water every so often, and above a chain whose held stablecoin supply grew over 24 hours they take those turns more often, wheel wider and climb higher — above one whose supply drained, less often, tighter and lower. At rest they carry the same reading as position: a filling harbour's birds sit out at the pier head, a draining harbour's tuck in at its root. The swing is compressed against a 3% full scale and carries no colour, so a busy quay reads as busy and never as distress",
      sourceField: "chains.chains[].change24hPct",
      questionAnswered: "Is this harbour filling or draining — is the chain holding more stablecoin supply than it did yesterday?",
      failureState: "the resting tempo, identical to a chain that genuinely did not move; the '24h supply change' row separates the two rather than letting a still quay mean either",
      domEquivalent: "dock detail '24h supply change' and '7d' held-supply rows naming the direction outright, plus the matching dock accessibility-ledger clause, both sitting next to the Net flow 24h issuance row so the two readings can be compared",
      reducedMotionEquivalent: "every gull stands on its harbour's pier deck — a composed still of birds at rest rather than a freeze in mid-wheel — and the tempo survives it as static geometry in the one channel a still frame can carry: a filling harbour's gulls stand further out along the pier head than a draining harbour's, which sit in at its root. The wheel's rate, width and height are motion channels and are simply absent here; the dock's '24h supply change' row carries the reading outright",
    },
    {
      id: "cue.ship.age-patina",
      target: { kind: "ship" },
      primaryChannels: ["color", "shape"],
      visual: "even weathered-wood value shift across the hull, softly worn edge highlights, and subtle verdigris on small fittings; sail cloth and issuer hue are untouched, and the treatment has no bands or streaks",
      sourceField: "stability.current.contributors[].ageDays, stablecoinMeta.launchDate, stablecoinMeta.milestones[], pegSummary.coins[].trackingSpanDays",
      questionAnswered: "Is this a fresh, seasoned, or veteran stablecoin hull, and how much service or tracking history supports that reading?",
      failureState: "neutral original hull finish; the In service since / tracked row says age evidence is unavailable rather than calling the ship fresh",
      domEquivalent: "ship detail 'In service since / tracked' row plus the accessibility-ledger age-patina clause; both name launch evidence, tracked days, the era, and the unavailable neutral state",
      reducedMotionEquivalent: "identical — age patina is an even static finish with no animation",
    },
    {
      id: "cue.ship.zone-weathering",
      target: { kind: "ship" },
      primaryChannels: ["color", "shape"],
      visual: "darkened waterline band and pale salt streaks on hulls holding Warning (light wear) or Danger (heavy wear) placements; Calm/Watch/Alert/Ledger hulls stay clean",
      sourceField: "pegSummary.coins[], stress.signals[] (risk-zone placement)",
      questionAnswered: "Has this ship been riding rough risk water?",
      failureState: "clean hull; risk zone still named in the detail placement row",
      domEquivalent: "ship detail placement explanation with named risk water area and accessibility ledger ship row",
      reducedMotionEquivalent: "same static baked wear (deterministic per ship and zone bucket)",
    },
    {
      id: "cue.area.danger-squall",
      target: { kind: "area" },
      primaryChannels: ["color", "motion"],
      visual: "screen-space rain streaks masked by the sea region-id field to DANGER water only, with the shared low mist veil and the region's existing heavier foam/chop; the sky gradient also stages darker as fleet threat climbs",
      sourceField: "pegSummary/stress DEWS band on areas (band === DANGER); maxActiveThreatLevel for the sky stage",
      questionAnswered: "Which named water is in active DANGER right now?",
      failureState: "no squall; the area detail atmosphere row still names the band",
      domEquivalent: "area detail and accessibility-ledger atmosphere rows name the local band and chop; lightning is described only as a fleet-storm capability because its active slots come from global weather",
      reducedMotionEquivalent: "frozen time-zero squall frame (streaks static, wash identical)",
    },
    {
      id: "cue.cemetery",
      target: { kind: "grave" },
      primaryChannels: ["shape", "size", "color"],
      visual: "cemetery graves",
      sourceField: "CEMETERY_ENTRIES",
      questionAnswered: "Which assets are dead or frozen?",
      failureState: "cemetery unavailable row",
      domEquivalent: "cemetery ledger rows",
      reducedMotionEquivalent: "same static tomb marker and cause plaque",
    },
  ];
}
