import type { VisualCue } from "./world-types";

export const LEGEND_MARK_ROWS = [
  {
    cueId: "cue.ship.zone-weathering",
    label: "Weathered hull",
    text: "Warning and Danger water can darken the hull; it marks rough risk water, not permanent damage or safety.",
  },
  {
    cueId: "cue.dock.congestion",
    label: "Stacked crates",
    text: "Cargo crates on a dock mean chain backing is narrowing or concentrated; empty quays do not certify safety.",
  },
  {
    cueId: "cue.dock.cargo-tide",
    label: "Cargo working the quay",
    text: "A single course of canvas-topped crates out along a harbour's pier means that chain's stablecoins were net minted over 24 hours; the same crates standing back along the quay edge mean they were net burned. An empty harbour means either nothing moved or issuance is not measured there, and the Net flow 24h row says which.",
  },
  {
    cueId: "cue.lighthouse.signal-mast",
    label: "Observatory signal mast",
    text: "Small pennants on the mast beside the observatory count the coins currently off peg (five is the top of the hoist); a dark cone joins them when the worst deviation is large. It reports today's readings, not a forecast.",
  },
  {
    cueId: "cue.lighthouse.high-water-mark",
    label: "Pale band on the lighthouse rocks",
    text: "A pale salt line climbing the lighthouse terrace records the worst index band of the last 30 days — how high the water got, not how it stands now. Unstained rock can also mean there was no history to read.",
  },
  {
    cueId: "cue.ship.cross-bearing-buoy",
    label: "Striped cross-bearing buoy",
    text: "A small black-and-white buoy riding beside a ship means its DEX price and its consensus price disagree. It says the two readings differ, not which one is right, and most ships have no buoy because no cross-check was run.",
  },
  {
    cueId: "cue.ship.audit-shield",
    label: "Steel-and-gold shield",
    text: "Major graded ships may carry a bluechip audit shield; the shield is a grade marker, not a blanket approval.",
  },
  {
    cueId: "cue.ship.nav-signal",
    label: "Blue mast signal",
    text: "A blue signal square marks a NAV-priced ledger asset — priced by attestation, not market peg; it is a pricing model, not a warning.",
  },
  {
    cueId: "cue.ship.yield-signal",
    label: "Green mast signal",
    text: "A green signal square with a gold pennant marks a yield-bearing coin; it says nothing about peg safety.",
  },
] as const;

export function buildVisualCueRegistry(): VisualCue[] {
  return [
    {
      id: "cue.lighthouse.psi",
      target: { kind: "lighthouse" },
      primaryChannels: ["glow", "opacity"],
      visual: "lighthouse beacon and beam state",
      sourceField: "stability.current.band",
      questionAnswered: "What is the overall Pharos Stability Index state?",
      failureState: "unlit/fogged lighthouse",
      domEquivalent: "lighthouse detail Score, Band, Trend, Composition, and top-contributor rows plus accessibility ledger lighthouse row",
      reducedMotionEquivalent: "static beacon state and lighthouse detail PSI rows",
    },
    {
      id: "cue.lighthouse.signal-mast",
      target: { kind: "lighthouse" },
      primaryChannels: ["shape", "size"],
      visual: "signal mast on the observatory terrace flying one small pennant per coin currently off peg (hoist of five) with a dark storm cone at the yardarm when the worst live deviation crosses the shared price-materiality gate",
      sourceField: "pegSummary.summary.activeDepegCount, pegSummary.summary.worstCurrent",
      questionAnswered: "How many stablecoins are off peg across the whole fleet right now, and is any one of them far enough off to count as a storm?",
      failureState: "bare mast; the lighthouse Signal mast row reads 'no peg summary tonight' and the Fleet peg row is absent",
      domEquivalent: "lighthouse detail Signal mast and Fleet peg rows plus the accessibility ledger lighthouse signal-mast clause",
      reducedMotionEquivalent: "same pennants and cone held at their composed time-zero pose",
    },
    {
      id: "cue.lighthouse.high-water-mark",
      target: { kind: "lighthouse" },
      primaryChannels: ["size", "color"],
      visual: "pale salt-crust courses banding the lighthouse terrace, one course per severity step of the worst Pharos Stability Index band reached in the trailing 30 days; bare stone when the worst reading never left the calmest band",
      sourceField: "stability.history[].band",
      questionAnswered: "Is this calm harbour one that has always been calm, or one that recovered from something recently?",
      failureState: "bare stone; the lighthouse 'Worst band, 30d' row reads 'Unstained — no index history to read', which is not the same as never having risen",
      domEquivalent: "lighthouse detail 'Worst band, 30d' row plus the accessibility ledger lighthouse high-water clause",
      reducedMotionEquivalent: "identical — the mark is a static record and never animates at any setting",
    },
    {
      id: "cue.lighthouse.beam-dwell",
      target: { kind: "lighthouse" },
      primaryChannels: ["motion", "position"],
      visual: "the beacon's sweep slowing as it crosses the bearing of the ship contributing most to the Pharos Stability Index, so the light lingers there each revolution",
      sourceField: "stability.current.contributors[0]",
      questionAnswered: "Which single ship is doing most to move the fleet-wide index right now?",
      failureState: "an even sweep at the fleet's stress tempo; the Beam bearing row is absent when no contributor is reported",
      domEquivalent: "lighthouse detail Beam bearing row and top-contributor list plus the accessibility ledger beam-bearing clause",
      reducedMotionEquivalent: "no sweep at all — the beam holds a static bearing on that same ship, and the Beam bearing row names which ship it is holding on",
    },
    {
      id: "cue.ship.cross-bearing-buoy",
      target: { kind: "ship" },
      primaryChannels: ["shape", "position"],
      visual: "small black-and-white striped buoy with a crossed topmark riding alongside any ship whose DEX price check disagrees with the consensus feed",
      sourceField: "pegSummary.coins[].dexPriceCheck.agrees",
      questionAnswered: "Are the two independent readings of this coin's price telling the same story?",
      failureState: "no buoy — which covers both 'the readings agree' and 'no check was run'; the detail row appears only on disagreement and the ledger clause only when a check ran at all",
      domEquivalent: "ship detail 'DEX cross-check' row on disagreement, plus the accessibility ledger DEX cross-check clause whenever a check ran",
      reducedMotionEquivalent: "identical — the buoy holds a static stand-off from its hull and moves only when the ship does, which reduced motion already stops",
    },
    {
      id: "cue.dock.size",
      target: { kind: "dock" },
      primaryChannels: ["size", "shape", "position"],
      visual: "dock footprint, Ethereum L2 extension placement, and harbor style",
      sourceField: "chains.chains[].id, chains.chains[].totalUsd, chains.chains[].topStablecoins",
      questionAnswered: "Which chains hold major stablecoin supply, which L2s belong to Ethereum harbor, and which stablecoins dominate each chain?",
      failureState: "dock unavailable state",
      domEquivalent: "dock detail Stablecoin supply, Harbor rank, Share of stablecoin supply, Concentration, and harbored-stablecoin rows plus dock ledger rows",
      reducedMotionEquivalent: "static dock footprint and dock ledger rows",
    },
    {
      id: "cue.ship.distance",
      target: { kind: "ship" },
      primaryChannels: ["position", "motion", "opacity"],
      visual: "ship placement from Calm Anchorage through Watch Breakwater, Alert Channel, Warning Shoals, and Danger Strait",
      sourceField: "pegSummary.coins[], stress.signals[]",
      questionAnswered: "Which stablecoins are under peg or DEWS stress?",
      failureState: "evidence caveat in ship detail",
      domEquivalent: "ship detail placement explanation with named risk water area, zone, and Stress driver row plus accessibility ledger stress-driver clause",
      reducedMotionEquivalent: "static idle position in the current risk-water area with named risk-water facts in DOM",
    },
    {
      id: "cue.ship.motion",
      target: { kind: "ship" },
      primaryChannels: ["motion", "position", "opacity"],
      visual: "ship route, chain footprint, mooring orbit variation, stale-evidence drift, 24h supply-change wake intensity, and chain-breadth dwell",
      sourceField: "stablecoins.peggedAssets[].chainCirculating, pegSummary.coins[], stress.signals[], placementEvidence.stale, change24hPct, chainPresence.length, ship.id (per-ship mooring orbit phase/radius offset)",
      questionAnswered: "Where can this ship dock, how broad is its chain footprint, which risk water anchors its route, how recent is its supply change, and how confident is its placement?",
      failureState: "reduced-motion static risk-water idle position with evidence caveat",
      domEquivalent: "ship detail Cycle tempo, 24h supply change, Chain footprint (extended dwell suffix), Evidence status facts, plus accessibility ledger ship row with 'cycle pace tracks supply tier, not transfers'",
      reducedMotionEquivalent: "risk-water or Ledger Mooring idle position without RAF",
    },
    {
      id: "cue.water.semantic-terrain",
      target: { kind: "area" },
      primaryChannels: ["color", "shape", "motion"],
      visual: "printed cartographic water labels over calm DEWS anchorage, watch breakwater chop, alert current, warning shoals, storm strait, and ledger-water texture",
      sourceField: "stress.signals[], pegSummary.coins[], stablecoinMeta.flags.navToken",
      questionAnswered: "Which named water areas encode calm, NAV-ledger, alert, warning, or danger conditions?",
      failureState: "generic water texture with DOM area detail still available",
      domEquivalent: "named area detail panel and accessibility ledger rows",
      reducedMotionEquivalent: "static semantic water texture and printed labels",
    },
    {
      // Reliable class reading is inspect-zoom only; fleet-zoom analysis belongs in the Class row and ledger.
      id: "cue.ship.hull",
      target: { kind: "ship" },
      primaryChannels: ["shape", "size"],
      visual: "ship class silhouette",
      sourceField: "stablecoinMeta.flags.governance",
      questionAnswered: "Is the stablecoin CeFi, CeFi-dependent, or DeFi?",
      failureState: "generic hull",
      domEquivalent: "ship detail class row",
      reducedMotionEquivalent: "same static hull silhouette",
    },
    {
      id: "cue.ship.scale",
      target: { kind: "ship" },
      primaryChannels: ["size", "shape"],
      visual: "compressed ship scale tier",
      sourceField: "stablecoins.peggedAssets[].circulating",
      questionAnswered: "Roughly how large is the stablecoin supply without letting outliers dominate the map?",
      failureState: "small default scale",
      domEquivalent: "ship detail market-cap row with fleet rank and share-of-fleet plus size-tier row",
      reducedMotionEquivalent: "same static compressed size tier",
    },
    {
      id: "cue.ship.audit-shield",
      target: { kind: "ship" },
      primaryChannels: ["shape", "color"],
      visual: "steel shield with gold chevron beside the signal mast on titan/heritage hulls with a bluechip-graded report card",
      sourceField: "reportCards.cards[].rawInputs.bluechipGrade",
      questionAnswered: "Does this major stablecoin carry a bluechip rating grade?",
      failureState: "no shield; detail row absent without a graded report card",
      domEquivalent: "ship detail Bluechip audit fact (folded into the class panel row) and accessibility ledger line",
      reducedMotionEquivalent: "same static shield",
    },
    {
      id: "cue.ship.nav-signal",
      target: { kind: "ship" },
      primaryChannels: ["shape", "color"],
      visual: "blue signal square with a cream pennant beside the mast on NAV-priced ledger assets",
      sourceField: "stablecoinMeta.flags.navToken",
      questionAnswered: "Is this asset NAV-priced by attestation rather than market-pegged?",
      failureState: "no mast signal; detail row absent for market-pegged coins",
      domEquivalent: "ship detail Class row folded Mast signal fact and accessibility ledger nav-pricing clause",
      reducedMotionEquivalent: "same static mast signal",
    },
    {
      id: "cue.ship.yield-signal",
      target: { kind: "ship" },
      primaryChannels: ["shape", "color"],
      visual: "green signal square with a gold pennant beside the mast on yield-bearing coins without NAV pricing",
      sourceField: "stablecoinMeta.flags.yieldBearing",
      questionAnswered: "Does this coin pay yield to holders?",
      failureState: "no mast signal; detail row absent for non-yield coins",
      domEquivalent: "ship detail Class row folded Mast signal fact and accessibility ledger yield clause",
      reducedMotionEquivalent: "same static mast signal",
    },
    {
      id: "cue.ship.safety-watch",
      target: { kind: "ship" },
      primaryChannels: ["shape", "color"],
      visual: "checkered safety-watch square on ships with D or F report-card grades",
      sourceField: "reportCards.cards[].overallGrade (D/F)",
      questionAnswered: "Which stablecoins carry a D or F safety grade watch overlay?",
      failureState: "no watch overlay; detail row absent for NR or missing report cards",
      domEquivalent: "ship detail Class row folded Safety grade plus accessibility ledger safety-grade and dimension rationale rows",
      reducedMotionEquivalent: "same static watch overlay with folded Class row and ledger rationale text",
    },
    {
      id: "cue.dock.congestion",
      target: { kind: "dock" },
      primaryChannels: ["shape", "size"],
      visual: "identical cargo crates stacking on the quay edge of docks whose chain backing is narrowing or concentrated",
      sourceField: "chains.chains[].healthFactors.backingDiversity",
      questionAnswered: "Is this chain's stablecoin backing diversified or concentrated?",
      failureState: "no crates; dock Backing diversity row absent without the health factor",
      domEquivalent: "dock detail Backing diversity row and accessibility ledger line",
      reducedMotionEquivalent: "same static crate stack",
    },
    {
      // The world's only FLOW cue. Everything else here reports a stock.
      id: "cue.dock.cargo-tide",
      target: { kind: "dock" },
      primaryChannels: ["position", "shape", "size"],
      visual: "a single course of canvas-topped crates standing seaward along a harbour's pier deck when its chains' stablecoins were net minted over 24 hours, and standing landward along the quay's outer edge when they were net burned; the run's length carries how one-sided the day's flow was",
      sourceField: "mintBurn.coins[].netFlow24hUsd, mintBurn.coins[].mintVolume24hUsd, mintBurn.coins[].burnVolume24hUsd, mintBurn.scope.chainIds (allocated across harbours by each coin's chain presence)",
      questionAnswered: "Is stablecoin supply being created or destroyed at this harbour right now?",
      failureState: "no crates — which covers both 'nothing moved' and 'issuance is not measured on this chain'; the Net flow 24h row separates the two rather than leaving an empty quay to mean either",
      domEquivalent: "dock detail 'Net flow 24h' row naming the direction outright plus gross mint and burn, the matching dock accessibility-ledger clause, and the fleet-issuance ledger line above the dock list",
      reducedMotionEquivalent: "identical — the cargo is a standing state and never animates at any setting, so there is nothing to freeze",
    },
    {
      id: "cue.ship.zone-weathering",
      target: { kind: "ship" },
      primaryChannels: ["color", "shape"],
      visual: "darkened waterline band and pale salt streaks on hulls holding Warning (light wear) or Danger (heavy wear) placements; Calm/Watch/Alert/Ledger hulls stay clean",
      sourceField: "pegSummary.coins[], stress.signals[] (risk-zone placement)",
      questionAnswered: "Has this ship been riding rough risk water?",
      failureState: "clean hull; risk zone still named in the detail placement row",
      domEquivalent: "ship detail placement explanation with named risk water area and accessibility ledger ship row",
      reducedMotionEquivalent: "same static baked wear (deterministic per ship and zone bucket)",
    },
    {
      id: "cue.area.danger-squall",
      target: { kind: "area" },
      primaryChannels: ["color", "motion"],
      visual: "localized rain curtain (storm-gray wash + slanted drifting streaks) over every DANGER-banded sea area, persistent while the band holds; the sky gradient also stages darker as fleet threat climbs",
      sourceField: "pegSummary/stress DEWS band on areas (band === DANGER); maxActiveThreatLevel for the sky stage",
      questionAnswered: "Which named water is in active DANGER right now?",
      failureState: "no squall; the area detail atmosphere row still names the band",
      domEquivalent: "area detail atmosphere description ('rain squall' wording) and accessibility ledger area row",
      reducedMotionEquivalent: "frozen time-zero squall frame (streaks static, wash identical)",
    },
    {
      id: "cue.cemetery",
      target: { kind: "grave" },
      primaryChannels: ["shape", "size", "color"],
      visual: "cemetery graves",
      sourceField: "CEMETERY_ENTRIES",
      questionAnswered: "Which assets are dead or frozen?",
      failureState: "cemetery unavailable row",
      domEquivalent: "cemetery ledger rows",
      reducedMotionEquivalent: "same static tomb marker and cause plaque",
    },
  ];
}
