import type { VisualCue } from "./world-types";

export function buildVisualCueRegistry(): VisualCue[] {
  return [
    {
      id: "cue.lighthouse.psi",
      target: { kind: "lighthouse" },
      primaryChannels: ["glow", "opacity"],
      visual: "lighthouse beacon and beam state",
      sourceField: "stability.current.band",
      questionAnswered: "What is the overall Pharos Stability Index state?",
      failureState: "unlit/fogged lighthouse",
      domEquivalent: "lighthouse detail panel",
      reducedMotionEquivalent: "static beacon state and lighthouse detail PSI rows",
    },
    {
      id: "cue.dock.size",
      target: { kind: "dock" },
      primaryChannels: ["size", "shape", "position"],
      visual: "dock footprint, Ethereum L2 extension placement, and harbor style",
      sourceField: "chains.chains[].id, chains.chains[].totalUsd, chains.chains[].topStablecoins",
      questionAnswered: "Which chains hold major stablecoin supply, which L2s belong to Ethereum harbor, and which stablecoins dominate each chain?",
      failureState: "dock unavailable state",
      domEquivalent: "dock ledger rows",
      reducedMotionEquivalent: "static dock footprint and dock ledger rows",
    },
    {
      id: "cue.ship.distance",
      target: { kind: "ship" },
      primaryChannels: ["position", "motion", "opacity"],
      visual: "ship placement from Calm Anchorage through Watch Breakwater, Alert Channel, Warning Shoals, and Danger Strait",
      sourceField: "pegSummary.coins[], stress.signals[]",
      questionAnswered: "Which stablecoins are under peg or DEWS stress?",
      failureState: "evidence caveat in ship detail",
      domEquivalent: "ship detail placement explanation with named risk water area and zone",
      reducedMotionEquivalent: "static idle position in the current risk-water area with named risk-water facts in DOM",
    },
    {
      id: "cue.ship.motion",
      target: { kind: "ship" },
      primaryChannels: ["motion", "position", "opacity"],
      visual: "ship route, docking cadence, mooring orbit variation, stale-evidence drift, 24h supply-change wake intensity, and chain-breadth dwell",
      sourceField: "stablecoins.peggedAssets[].chainCirculating, pegSummary.coins[], stress.signals[], placementEvidence.stale, change24hPct, chainPresence.length, ship.id (per-ship mooring orbit phase/radius offset)",
      questionAnswered: "Where can this ship dock, how often does it visit, which risk water anchors its route, how recent is its supply change, and how confident is its placement?",
      failureState: "reduced-motion static risk-water idle position with evidence caveat",
      domEquivalent: "ship detail Cycle tempo, 24h supply change, Docking cadence (extended dwell suffix), Evidence status facts, plus accessibility ledger ship row",
      reducedMotionEquivalent: "risk-water or Ledger Mooring idle position without RAF",
    },
    {
      id: "cue.water.semantic-terrain",
      target: { kind: "area" },
      primaryChannels: ["color", "shape", "motion"],
      visual: "printed cartographic water labels over calm DEWS anchorage, watch breakwater chop, alert current, warning shoals, storm strait, and ledger-water texture",
      sourceField: "stress.signals[], pegSummary.coins[], stablecoinMeta.flags.navToken",
      questionAnswered: "Which named water areas encode calm, NAV-ledger, alert, warning, or danger conditions?",
      failureState: "generic water texture with DOM area detail still available",
      domEquivalent: "named area detail panel and accessibility ledger rows",
      reducedMotionEquivalent: "static semantic water texture and printed labels",
    },
    {
      id: "cue.ship.hull",
      target: { kind: "ship" },
      primaryChannels: ["shape", "size"],
      visual: "ship class silhouette",
      sourceField: "stablecoinMeta.flags.governance",
      questionAnswered: "Is the stablecoin CeFi, CeFi-dependent, or DeFi?",
      failureState: "generic hull",
      domEquivalent: "ship detail class row",
      reducedMotionEquivalent: "same static hull silhouette",
    },
    {
      id: "cue.ship.rigging",
      target: { kind: "ship" },
      primaryChannels: ["shape", "position"],
      visual: "ship rigging style",
      sourceField: "stablecoinMeta.flags.governance",
      questionAnswered: "Which governance class controls the base ship model?",
      failureState: "generic rigging",
      domEquivalent: "ship detail class row",
      reducedMotionEquivalent: "same static rigging silhouette",
    },
    {
      id: "cue.ship.scale",
      target: { kind: "ship" },
      primaryChannels: ["size", "shape"],
      visual: "compressed ship scale tier",
      sourceField: "stablecoins.peggedAssets[].circulating",
      questionAnswered: "Roughly how large is the stablecoin supply without letting outliers dominate the map?",
      failureState: "small default scale",
      domEquivalent: "ship detail market-cap and size-tier rows",
      reducedMotionEquivalent: "same static compressed size tier",
    },
    {
      id: "cue.ship.consensus-rigging",
      target: { kind: "ship" },
      primaryChannels: ["shape", "position"],
      visual: "shroud-line rigging density on standard hulls at inspect zoom (full source agreement rigs the full set; disagreement leaves it sparse)",
      sourceField: "stablecoins.peggedAssets[].consensusSources, stablecoins.peggedAssets[].agreeSources",
      questionAnswered: "How many independent price sources agree on this stablecoin's price?",
      failureState: "no rigging-density cue; detail row absent when no consensus data",
      domEquivalent: "ship detail Source consensus fact (folded into the market-cap panel row) and accessibility ledger line",
      reducedMotionEquivalent: "same static rigging lines",
    },
    {
      id: "cue.ship.audit-shield",
      target: { kind: "ship" },
      primaryChannels: ["shape", "color"],
      visual: "steel shield with gold chevron beside the signal mast on titan/heritage hulls with a bluechip-graded report card",
      sourceField: "reportCards.cards[].rawInputs.bluechipGrade",
      questionAnswered: "Does this major stablecoin carry a bluechip rating grade?",
      failureState: "no shield; detail row absent without a graded report card",
      domEquivalent: "ship detail Bluechip audit fact (folded into the class panel row) and accessibility ledger line",
      reducedMotionEquivalent: "same static shield",
    },
    {
      id: "cue.dock.congestion",
      target: { kind: "dock" },
      primaryChannels: ["shape", "size"],
      visual: "identical cargo crates stacking on the quay edge of docks whose chain backing is narrowing or concentrated",
      sourceField: "chains.chains[].healthFactors.backingDiversity",
      questionAnswered: "Is this chain's stablecoin backing diversified or concentrated?",
      failureState: "no crates; dock Backing diversity row absent without the health factor",
      domEquivalent: "dock detail Backing diversity row and accessibility ledger line",
      reducedMotionEquivalent: "same static crate stack",
    },
    {
      id: "cue.cemetery",
      target: { kind: "grave" },
      primaryChannels: ["shape", "size", "color"],
      visual: "cemetery graves",
      sourceField: "CEMETERY_ENTRIES",
      questionAnswered: "Which assets are dead or frozen?",
      failureState: "cemetery unavailable row",
      domEquivalent: "cemetery ledger rows",
      reducedMotionEquivalent: "same static tomb marker and cause plaque",
    },
  ];
}
